theme = "gruber-darker"

[editor]
# line-number = "relative"
mouse = true
cursorline = true
true-color = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "bar"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = false
