theme = "gruber-darker"

[editor]
# line-number = "relative"
mouse = true
color-modes = true
cursorline = true
true-color = true
# cursorcolumn = true
# bufferline = "always"
# rulers = [60]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "bar"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
# display-inlay-hints = true



# [editor.whitespace]
# render = "all"

# [editor.indent-guides]
# render = true
# character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 1


