# Author : Mehedi Hasan <mehedi.r137@gmail.com>
# The theme is a port of: https://github.com/rexim/gruber-darker-theme

"attribute" = "fg1"
"keyword" = { fg = "yellow0" , modifiers = ["bold"]}
"keyword.directive" = "quartz"
"namespace" = "quartz"
"punctuation" = "fg1"
"punctuation.delimiter" = "fg1"
"operator" = "fg1"
"special" = { fg = "yellow0", modifiers = ["bold"] }
# "variable.other.member" = "green0"
"variable" = "fg1"
"variable.builtin" = {  fg = "yellow0", modifiers = ["bold"]}
"variable.parameter" = "fg1"
"type" = "quartz"
"type.builtin" = "quartz"
"constructor" = { fg = "quartz" }
"function" = "niagara0"
"function.builtin" = "yellow0"
# "function.method" = { fg = "green0" }
# "function.macro" = "quartz"
# "function.special" = { fg = "green0" }
"tag" = "niagara0"
"comment" = { fg = "brown" }
"constant.character" = { fg = "green0" }
"constant.character.escape" = { fg = "yellow0" }
# "constant.builtin" = { fg = "yellow0" }
"constant.builtin" = { fg = "yellow0", modifiers = ["bold"] }
"string" = "green0"
"constant.numeric" = "wisteria"
"label" = "fg1"
"module" = "aqua1"

"diff.plus" = "green1"
"diff.delta" = "orange1"
"diff.minus" = "red0"

"warning" =  "orange1"
"error" = "red0"
"info" = "aqua1"
"hint" = "blue1"

"ui.background" = { bg = "bg0", fg = "fg0" }
"ui.linenr" = { fg = "bg4" }
"ui.linenr.selected" = { fg = "yellow0" }
"ui.cursorline" = { bg = "bg1" }
"ui.statusline" = { fg = "fg1", bg = "bg1" }
"ui.statusline.normal" = { fg = "fg1", bg = "bg1" }
"ui.statusline.insert" = { fg = "fg1", bg = "red3" }
"ui.statusline.select" = { fg = "fg1", bg = "orange0" }
"ui.statusline.inactive" = { fg = "fg3", bg = "bg1" }
"ui.popup" = { bg = "bg6" }
"ui.window" = { bg = "bg1" }
"ui.help" = { bg = "bg6", fg = "fg1" }
"ui.text" = { fg = "fg1" }
"ui.text.focus" = { bg = "bg5", modifiers = ["bold"] }
"ui.selection" = { bg = "bg2" }
"ui.selection.primary" = { bg = "bg5" }
"ui.cursor.primary" = { bg = "fg0", fg = "niagara1" }
"ui.cursor.match" = { bg = "yellow1" }
"ui.menu" = { fg = "fg1", bg = "bg6" }
"ui.menu.selected" = { fg = "fg1", bg = "bg5", modifiers = ["bold"] }
"ui.virtual.whitespace" = "bg2"
"ui.virtual.ruler" = { bg = "red3" }
"ui.virtual.inlay-hint" = { fg = "gray1" }
"ui.virtual.wrap" = { fg = "bg2" }

"diagnostic.warning" = { underline = { color = "orange1", style = "dashed" } }
"diagnostic.error" = { underline = { color = "red3", style = "dashed" } }
"diagnostic.info" = { underline = { color = "aqua1", style = "dashed" } }
"diagnostic.hint" = { underline = { color = "blue1", style = "dashed" } }

"markup.heading" = "aqua1"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "green1", modifiers = ["underlined"] }
"markup.link.text" = "red3"
"markup.raw" = "red3"

[palette]
fg0 =      "#e4e4ef"
fg1 =      "#e4e4ef"
fg2 =      "#f5f5f5"
fg3 =      "#a89984" 
bg0 =      "#181818"
bg1 =      "#282828"
bg2 =      "#453d41"
bg4 =      "#52494e"
bg5 =      "#404040"
bg6 =     "#232323"
gray1 =    "#928374"
red0 =     "#f43841"
red1 =     "#ff4f58"
red2 =     "#2B0A0B"
red3 =     "#fb4934"
green0 =   "#73c936"
green1 =   "#b8bb26"
yellow0 =  "#ffdd33"
yellow1 =  "#655814"
blue1 =    "#83a598"
orange0 =  "#d65d0e"
orange1 =  "#fe8019"
brown =    "#cc8c3c"
quartz =   "#95a99f"
niagara0 = "#96a6c8"
niagara1 = "#303540"
wisteria = "#9e95c7"
aqua1 =    "#8ec07c"


